util.cbaw;
set light_count,10;
set spec_count,1;
set shininess, 200;
set specular,1;
set ambient,0.2;
set direct,0.8;
set reflect,1.5;
set ray_shadow_decay_factor, 0.1;
set ray_shadow_decay_range, 2;
set depth_cue, 0.2;
set ray_shadow, on;
set antialias, 2;
set ray_trace_mode, 1;
set ray_trace_gain, 0.1;
set ray_trace_disco_factor, 1;
set ray_trace_fog, 0.5;
bg_color white; 
bond resname FE1, resname OY1 and name O1;
bond resname FE1, resname SC1 and name O1;
bond resname FE1, resname HD1 and name NE2;
bond resname FE1, resname HD2 and name NE2;
# Edit the selection that is named ligand here.;
select ligand, resname FE1+OY1+HD1+HD2+SC1+GU1+MEL;
set sphere_scale, 0.15, ligand;
set stick_radius, 0.05, ligand;
show sticks, ligand;    
show spheres, ligand;