set ambient 0.5;
set reflect 0.5;
set direct 0.45;
set spec_direct 0;
set spec_direct_power 55;
set light_count, 2;
set edit_light, 1;
set spec_count, -1;
set shininess, 0;
set spec_reflect, -0.01;
set specular, 0;
set specular_intensity, 0;  
set ambient_occlusion_mode, 0;
set ambient_occlusion_scale, 25;
set ambient_occlusion_smooth, 10;
set power, 1;
set reflect_power, 1;
set ray_trace_mode, 1;
hide everything; 
bond resname FE1, resname OY1 and name O1;
bond resname FE1, resname SC1 and name O1;
bond resname FE1, resname HD1 and name NE2;
bond resname FE1, resname HD2 and name NE2;
# Edit the selection that is named ligand here.;
select ligand, resname FE1+OY1+HD1+HD2+SC1+GU1+MEL;
set sphere_scale, 0.15, ligand;
set stick_radius, 0.05, ligand;
show sticks, ligand;    
show spheres, ligand;